packetType =

  # Client Packets
	CLIENT_AUTH			         		: 1
	CLIENT_PRELOAD_UPDATE	  		: 10

	# Server Packets
	SERVER_ACCESS_DECLINED    	: 11
	SERVER_ACCESS_GRANTED     	: 12
	SERVER_GAME_START						: 13
	SERVER_OBJECT_IN						: 16
	SERVER_PLAYER_INIT_STATS		: 35
	SERVER_PLAYER_UPDATE_STATS	: 36
	SERVER_PRELOAD_DATA					: 50
	SERVER_WAVE_INIT						: 60
	SERVER_WAVE_UPDATE					: 61

return packetType