constants =
	TERRAIN_DEFAULT_WIDTH : 64
	TERRAIN_DEFAULT_HEIGHT : 64
	TERRAIN_DEFAULT_SMOOTHNESS : 0.1
	TERRAIN_DEFAULT_ZSCALE : 0
	TERRAIN_MIN_WIDTH : 1
	TERRAIN_MIN_HEIGHT : 1
	TERRAIN_MIN_SMOOTHNESS : 0.1
	TERRAIN_MIN_ZSCALE : 0
	TERRAIN_MAX_WIDTH : 128
	TERRAIN_MAX_HEIGHT : 128
	TERRAIN_MAX_SMOOTHNESS : 5
	TERRAIN_MAX_ZSCALE : 500
	TERRAIN_STEPS_WIDTH : 1
	TERRAIN_STEPS_HEIGHT : 1
	TERRAIN_STEPS_SMOOTHNESS : 0.1
	TERRAIN_STEPS_ZSCALE : 20

return constants