variables =
	SCREEN_TOP : 0
	SCREEN_LEFT : 0
	SCREEN_WIDTH : window.innerWidth
	SCREEN_HEIGHT : window.innerHeight
	
	MOUSE_POSITION_X : 0
	MOUSE_POSITION_Y : 0
	MOUSE_MOVED : false
	MOUSE_PRESSED_LEFT : false
	MOUSE_PRESSED_MIDDLE : false
	MOUSE_PRESSED_RIGHT : false
	
	RENDERER_TYPE_CANVAS : 'canvas'
	RENDERER_TYPE_WEBGL : 'webgl'
	
	CAMERA_TYPE_RTS: 'RTS_CAMERA'
	CAMERA_TYPE_FREE: 'FREE_CAMERA'

return variables