variables =
	SCREEN_TOP : 0
	SCREEN_LEFT : 0
	SCREEN_WIDTH : window.innerWidth
	SCREEN_HEIGHT : window.innerHeight
	
	RENDERER_TYPE_CANVAS : 'canvas'
	RENDERER_TYPE_WEBGL : 'webgl'
	
	VIEWPORT_TYPE_RTS: 'VIEWPORT_TYPE_RTS'
	VIEWPORT_TYPE_EDITOR: 'VIEWPORT_TYPE_EDITOR'

return variables